package strings

import "fmt"

func Strings(){
	fmt.Print("==================== ==================== ===================\n")
	fmt.Println("...........................STRINGS...........................")
	fmt.Print("==================== ==================== ===================\n")
	// fmt.Println("1. Basics ...")
	// fmt.Println("******************** ******************** *******************")
	// StringBasics()
	// fmt.Print("==================== ==================== ===================\n")
	// fmt.Println("2. Longest sub-strings sans repeating characters ...")
	// fmt.Println("******************** ******************** *******************")
	// LongestSubstringSansRepeatingChars()
	// fmt.Print("==================== ==================== ===================\n")
	// fmt.Println("3. Longest sub-strings with character replacement ...")
	// fmt.Println("******************** ******************** *******************")
	// LongestSubstringCharReplacement()
	// fmt.Print("==================== ==================== ===================\n")
	// fmt.Println("4. Minimum window sub-string ...")
	// fmt.Println("******************** ******************** *******************")
	// MinimumWindowSubstring()
	// fmt.Print("==================== ==================== ===================\n")
	// fmt.Println("5. Valid anagram ...")
	// fmt.Println("******************** ******************** *******************")
	// ValidAnagram()
	// fmt.Print("==================== ==================== ===================\n")
	// fmt.Println("6. Group anagrams ...")
	// fmt.Println("******************** ******************** *******************")
	// GroupAnagrams()
	// fmt.Print("==================== ==================== ===================\n")
	// fmt.Println("7. Valid parentheses ...")
	// fmt.Println("******************** ******************** *******************")
	// ValidParentheses()
	// fmt.Print("==================== ==================== ===================\n")
	// fmt.Println("8. Longest palindromic sub-string ...")
	// fmt.Println("******************** ******************** *******************")
	// LongestPalindromicSubstring()
	// fmt.Print("==================== ==================== ===================\n")
	// fmt.Println("9. Palindromic sub-strings ...")
	// fmt.Println("******************** ******************** *******************")
	// PalindromicSubstrings()
	// fmt.Print("==================== ==================== ===================\n")
	// fmt.Println("10. Encode and decode strings ...")
	// fmt.Println("******************** ******************** *******************")
	// EncodeDecodeString()
	// fmt.Print("==================== ==================== ===================\n")
}